# Generated by Django 4.0.5 on 2022-07-05 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=64, verbose_name='user name')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last name')),
                ('profile', models.ImageField(blank=True, default='default.png', null=True, upload_to=market.models.profile_images, verbose_name='profile')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bascket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='product name')),
                ('description', models.TextField(verbose_name='description')),
                ('registerd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='price')),
                ('discount_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='dicount price')),
                ('remaining', models.PositiveBigIntegerField(verbose_name='remaining products')),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='shop name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=market.models.shop_images, verbose_name='logo')),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_founder', models.BooleanField(default=False)),
                ('can_edit_shop', models.BooleanField(default=False)),
                ('can_open_shelf', models.BooleanField(default=False)),
                ('can_edit_shelf', models.BooleanField(default=False)),
                ('can_delete_shelf', models.BooleanField(default=False)),
                ('can_add_product', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='owners',
            field=models.ManyToManyField(related_name='shops', related_query_name='shop', through='market.ShopOwnership', to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(related_name='shops', related_query_name='shop', through='market.Shelf', to='market.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(verbose_name='number of products')),
                ('bascket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.bascket')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shelf')),
            ],
        ),
        migrations.AddField(
            model_name='bascket',
            name='orders',
            field=models.ManyToManyField(related_name='orders', related_query_name='order', through='market.Order', to='market.shelf', verbose_name='orders'),
        ),
        migrations.AddField(
            model_name='bascket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('shelf'), django.db.models.expressions.F('bascket'), name='unique_shelf_bascket'),
        ),
    ]
