# Generated by Django 4.0.5 on 2022-07-05 11:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bascket',
            new_name='Basket',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_shelf_bascket',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bascket',
            new_name='basket',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='products',
            new_name='shelves',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('shelf'), django.db.models.expressions.F('basket'), name='unique_shelf_bascket'),
        ),
    ]
