# Generated by Django 4.0.5 on 2022-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_bascket_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
