# Generated by Django 4.0.5 on 2022-07-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('market', '0003_shelf_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(condition=models.Q(('submitted', False)), fields=('user',), name='user_not_submitted_unique'),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(condition=models.Q(('submitted', False)), fields=('session',), name='session_not_submitted_unique'),
        ),
    ]
