# Generated by Django 4.0.5 on 2022-07-15 08:49

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_basket_session_alter_basket_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopownership',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('shop'), django.db.models.expressions.F('owner'), name='unique_shop_owner'),
        ),
    ]
